name: release-actions-test

on: 
  release:
    types: [published]

jobs:
  greeter:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting the release
        run: echo Congratulations on publishing a new release ${{ github.event.release.tag_name }}!
