name: Update Version with commit

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          #token: ${{ secrets.GITHUB_TOKEN }} # You need to create your own token with commit rights
          token: ${{ secrets.ALEX_TOKEN }}
          ref: main # The branch you want to commit to


      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          #files: README.md # List of files to update
          files: version.txt
          #prefix: "file-updater-for-release@" # Prefix before the version, default is: ""
          #prefix:
          with-checkout: false # If you don't want to checkout the repo, default is: true
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .
          #message: 'update files'
          message: 'update version.txt'
